SELECT * FROM customer_shopping.customer_shopping;

--- Q-1 What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) AS Total_Revenue
FROM customer_shopping.customer_shopping
GROUP BY gender;

--- Q-2 Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,purchase_amount
FROM customer_shopping.customer_shopping
WHERE discount_applied = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_shopping.customer_shopping);

--- Q-3 Which are the top 5 products with the highest average review rating ?
SELECT item_purchased, ROUND(AVG(review_rating),2) AS Avg_Rating
FROM customer_shopping.customer_shopping
GROUP BY item_purchased
ORDER BY Avg_Rating DESC
LIMIT 5;

--- Q-4 Compare the average Purchase Amounts between Standard and Express Shipping?
SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS Avg_purchase_amount
FROM customer_shopping.customer_shopping
WHERE shipping_type='Standard' OR shipping_type='Express'
GROUP BY shipping_type;

--- Q-5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
	COUNT(customer_id) AS No_of_Customers,
    ROUND(AVG(purchase_amount),2) AS Avg_purchase_amount,
    ROUND(SUM(purchase_amount),2) AS Total_revenue
FROM customer_shopping.customer_shopping
GROUP BY subscription_status;

--- Q-6 Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, ROUND((SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)*100.0) / COUNT(*),2) AS Discount_Percentage
FROM customer_shopping.customer_shopping
GROUP BY item_purchased
ORDER BY Discount_Percentage DESC
LIMIT 5;

--- Q-7 Segment customers into New, Returning and Loyal based on their total number of previous purchases, and show the count of each segment
WITH customer_type AS(
	SELECT customer_id, previous_purchases,
		CASE
			WHEN previous_purchases = 1 THEN 'New'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
            END AS customer_segment
            FROM customer_shopping.customer_shopping)
SELECT customer_segment, COUNT(*) AS Numbers_of_Customers
FROM customer_type
GROUP BY customer_segment;

--- Q-8 What are the top 3 most purchased products within each category?
WITH item_counts AS(
	SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
    ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rnk
    FROM customer_shopping.customer_shopping
    GROUP BY category, item_purchased)
SELECT item_rnk, category, item_purchased, total_orders
FROM item_counts
WHERE item_rnk <= 3;

--- Q-9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer_shopping.customer_shopping
WHERE previous_purchases > 5
GROUP BY subscription_status;


--- Q-10 What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer_shopping.customer_shopping
GROUP BY age_group
ORDER BY total_revenue DESC;